services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ElixisGroup\GcpSecretManagerBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../Tests/'

    ElixisGroup\GcpSecretManagerBundle\DependencyInjection\GcpSecretManagerClientFactory: ~

    gcp.secret_manager.secretManagerServiceClient:
        class: Google\Cloud\SecretManager\V1\SecretManagerServiceClient
        factory: ['@ElixisGroup\GcpSecretManagerBundle\DependencyInjection\GcpSecretManagerClientFactory', 'createClient']
        arguments:
            - '%gcp.secret_manager.keyfilepath%'

    gcp.secret_manager.secretManagerProvider:
        class: ElixisGroup\GcpSecretManagerBundle\Provider\GcpSecretManagerProvider
        public: true
        arguments:
            - '@gcp.secret_manager.secretManagerServiceClient'
            - '%gcp.secret_manager.project_id%'
    
    ElixisGroup\GcpSecretManagerBundle\Provider\GcpSecretManagerProvider:
        arguments:
            - '@gcp.secret_manager.secretManagerServiceClient'
            - '%gcp.secret_manager.project_id%'

    gcp.secret_manager.secretManagerEnvVarProcessor:
        class: ElixisGroup\GcpSecretManagerBundle\GcpSecretManagerEnvVarProcessor
        tags: 
            - 'container.env_var_processor'
        arguments: 
            - '@gcp.secret_manager.secretManagerProvider'
            - '%gcp.secret_manager.ignore%'
            - '%gcp.secret_manager.delimiter%'